# Numpy

**NumPy** is a core library for scientific computing with Python. NumPy is centered around a powerful N-dimensional array object. 
<br>
In this tutorial, the data will be contained in numpy arrays. We will mainly use 2-dimensional arrays (matrices).

**NumPy**は、Python用の科学計算用のライブラリです。 NumPyはN次元配列オブジェクトを中心にしています。
<br>
この実習で使うデータはNumPy配列に入れます。主に2次元配列（行列）を使用します。

To use numpy, you have to __import__ the `numpy` __package__ in your notebook in order to have access to the library.

NumPyを使用するには、以下のように `numpy` __パッケージ__を__インポート__する必要があります。

In [1]:
import numpy as np

Importing `numpy` with the alias `np` is a common practice in python. This alias will be used in all the notebooks. 
<br>
(An alias is like a _new name_. Usually a shorter name so that it is easier to type.)

エイリアス`np`を使用して`numpy`をインポートすることは、Pythonで一般的です。 このエイリアスは、すべてのノートブックで使用されます。
<br>
（エイリアスは_新しい名前_のようなものです。通常は入力しやすいように短い名前にします。）

You can think of a matrix as a convenient way to represent and process the information contained in a table.
<br>
Let us consider the following table:

行列は、テーブルに含まれる情報を表現するためな方法と考えられます。
<br>
次の表について考えてみましょう。

| year |  2010 | 2011 | 2012 | 2013 | 2014 |
| ---  |   --- |  --- |  --- |  --- |  --- |
| cost per product |   7  |   6 | 5    |  4  |   5  |
| number of products|   200|  250  | 300 | 150 | 200 | 

The corresponding matrix is a structure containing only the data:

該当する行列は、データのみを含む構造です。

$M = \begin{bmatrix}
 7 & 6 & 5 & 4 & 5\\
 200 & 250 & 300 & 150 & 200
\end{bmatrix}$
<br>

The number of products in 2012 is in the third cell in the second row of the table.
This correspond to the third element in the second row of $M$.
<br>
Using `numpy`'s notation, this matrix is written as:

例えば、2012年の製品数は、表の2行目の3番目のセルに入っています。
これは、$M$の2行目の3番目の要素に対応します。
<br>
`numpy`の表記を使用すると、この行列は次のように記述されます。

M = [
<br>
[7, 6, 5, 4, 5],
<br>
[200, 250, 300, 150, 200]
<br>
]
<br>

and the third element in the second row is accessed by M[1,2] (by convention indexing starts at 0).

そして、2行目の3番目の要素はM[1,2]によってアクセスできます（インデックスは0から始まります！）。

Let us explain the numpy notation using the following matrix of size 2x4:

サイズ2x4の次の行列を使用して、numpy表記について説明します。

[
<br>
[0, 1, 2, 3],
<br>
[4, 5, 6, 7]
<br>
]

The first row is [0, 1, 2, 3] and the second row is [4, 5, 6, 7].
<br>
To write a matrix in numpy, you can use the `array` keyword as follows:

最初の行は[0、1、2、3]で、2番目の行は[4、5、6、7]です。
<br>
numpyで行列を書き込むには、次のように`array`キーワードを使用します。

In [2]:
np.array([
    [0, 1, 2, 3], 
    [4, 5, 6, 7]
])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

The following formatting is equivalent:

改行する必要はありません。次のコードは上記と同じです。

In [3]:
np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

A numpy array is an object that can be assigned to a variable.

numpy配列は、変数に割り当てることができます。

In [4]:
M = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

In python, the function `type( )` gives you the type of an object. The variable `M` is a numpy array (`numpy.ndarray`).

Pythonでは、関数`type( )`がオブジェクトのタイプを出力します。 変数`M`はnumpy配列です (`numpy.ndarray`)。

In [5]:
print(type(M))

<class 'numpy.ndarray'>


#### Accessing array elements / 配列要素へのアクセス

There are convenient ways to access a single element of a numpy array (note the indexing starting at 0):

numpy配列の単一の要素に以下のうようにアクセスできます（インデックスが0から始まることに注意してください）。

In [6]:
print("M[0,0]=", M[0,0])
print("M[0,1]=", M[0,1])
print("M[1,3]=", M[1,3])

M[0,0]= 0
M[0,1]= 1
M[1,3]= 7


or sub blocks of elements:

要素のサブブロックの場合：

In [7]:
print("M[0:2,0]=", M[0:2,0])
print("M[0,1:3]=", M[0,1:3])
print("M[0:2,1:3]=", M[0:2,1:3])

M[0:2,0]= [0 4]
M[0,1:3]= [1 2]
M[0:2,1:3]= [[1 2]
 [5 6]]


It is possible to access the rows:

行列の行にアクセス：

In [8]:
print("M[0,:]=", M[0,:])
print("M[1,:]=", M[1,:])

M[0,:]= [0 1 2 3]
M[1,:]= [4 5 6 7]


or the columns:

行列の列にアクセス：

In [9]:
print("M[:,0]=", M[:,0])
print("M[:,1]=", M[:,1])
print("M[:,2]=", M[:,2])
print("M[:,3]=", M[:,3])

M[:,0]= [0 4]
M[:,1]= [1 5]
M[:,2]= [2 6]
M[:,3]= [3 7]


Note that:
- the first index is `0` 
- the notation `i:j` means from index `i` to index `j-1`
- the notation `:` means all the indices on that dimension


注意点：
- 最初のインデックスは`0`です
- 表記`i:j`は、インデックス`i`からインデックス`j-1`までを意味します
- 表記`:`は、その行または列のすべてのインデックスを意味します

The notation `:` is also useful to split an array in two:
- `:i` means from beginning up to element `i-1` 
- `i:` means from element `i` until the end

表記`:`は、配列を2つに分割する場合にも役立ちます。
- `:i`は最初から要素`i-1`までを意味します
- `i:`は要素`i`から最後までを意味します

In [10]:
print("M[0,:]=", M[0,:])
print("M[0,:2]=", M[0,:2])
print("M[0,2:]=", M[0,2:])

M[0,:]= [0 1 2 3]
M[0,:2]= [0 1]
M[0,2:]= [2 3]


For containing the indices it is possible to use a python list or a numpy array.

インデックスはpythonリストまたはnumpy配列に入れることができます。

In [11]:
print("M=", M)

# using python list / リストを使う
l = [0, 2]
print("l=", l)
print("M[0, l]=", M[0, l])

# using numpy array / numpy行列を使う
i = np.array([0, 2])
print("i=", i)
print("M[0, i]=", M[0, i])

M= [[0 1 2 3]
 [4 5 6 7]]
l= [0, 2]
M[0, l]= [0 2]
i= [0 2]
M[0, i]= [0 2]


NumPy arrays are not limited to 2 dimensions (a dimension is usually called an __axis__).

NumPyでは３つ以上の次元の配列も使用できます（次元は通常__axis__（軸）と呼ばれます）。

#### Functions with numpy arrays / numpy配列を使う関数

A numpy array contains many useful member variables and functions.

numpy配列には、多くの有用なメンバー変数と関数が含まれています。

For example, the member `shape` contains the list of the axis lengths:

たとえば、変数`shape`（形状）には軸の長さのリストが入っています。

In [12]:
M.shape

(2, 4)

Numpy provides several functions to create arrays using a shape parameter as input.
<br>
For example an array of zeros of size 3x2:

形状パラメーターを入力として使用して配列を作成するためのいくつかの関数があります。
<br>
たとえば、すべての要素がゼロの配列（行列の大きさは5x2）。

In [13]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

or an array of ones of size 5x2:

または要素がすべて1の配列（大きさは5x2）。

In [14]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

Numpy arrays are not limited to two __axes__:

３次元の配列の作り方

In [15]:
A = np.zeros((2, 2, 3))
print("A before:\n", A)
A[1, 1, 0] = 5
print("A after:\n", A)

A before:
 [[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
A after:
 [[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [5. 0. 0.]]]


Many common functions for matrices are implemented.
For example, the function `mean()` gives you the mean value.

行列の多くの一般的な関数が実装されています。
たとえば、関数`mean()`は平均値を提供します。

In [16]:
# Mean value computed on all elements / すべての要素の平均値
print(M.mean())

3.5


In [17]:
# Columns means computed along the rows / 列の平均
column_means = M.mean(axis=0)
print(column_means)

[2. 3. 4. 5.]


In [18]:
# This is also a numpy array / 関数の結果もNumpyの配列です
print(type(column_means))

<class 'numpy.ndarray'>


In [19]:
# Shape of column_means / 列の平均の形状
print(column_means.shape)

(4,)


In [20]:
# Row means computed along the columns / 行の平均
row_means = M.mean(axis=1)
print(row_means)
print(row_means.shape)

[1.5 5.5]
(2,)


Note that it is also possible to use the `mean` and other functions of the` numpy` package itself. The result is the same as using the functions of the object.
<br>
`numpy`パッケージ自体の`mean`などの関数を使用することもできます。得られる結果はオブジェクトの関数を使用した場合と同じです。

In [21]:
np.mean(M, axis=0)

array([2., 3., 4., 5.])

Numpy arrays support element wise operations.
<br>
Numpy配列で要素ごとの演算ができます。

In [22]:
row_0 = M[0,:]
row_1 = M[1,:]
print(row_0 + 2.0 * row_1)
print(row_0 * row_1)

[ 8. 11. 14. 17.]
[ 0  5 12 21]


Note that `*` is an element-wise product.
<br>
`*`は要素ごとの積であることに注意してください。

The dot product can be calculated like this.
<br>
内積は次のように計算できます。

In [23]:
print(row_0.dot(row_1))
# or / または
# print(np.dot(row_0, row_1))

38


Numpy arrays support many more operations.
<br>
These simple data manipulations will be combined with other functions during the practice.

Numpy配列はさらに多くの操作をサポートしています。
<br>
実習ではこれらの単純な関数を組み合わさることによってデータ処理を行います。

#### Example with data loading from file / ファイルからデータ読み取りを使った例

For illustration we will use the "iris dataset".
<br>
The dataset contains a set of 150 records with five attributes: flower type, sepal length and width, petal length and width.

説明のために、「アヤメのデータセット」を使用します。
<br>
データセットには花の測定データが150含まれています。それぞれの花に対して次の5つのデータが入っています：花の種類、がく（萼）の長さと幅、花びらの長さと幅。
<br><br>

<center>
    <img src="./img/petal-sepal.jpg" width="160"> Petal (花びら) and sepal (がく)
</center>
<br>
There are 50 samples from each of the 3 following species of flowers.

次の3種類の花からそれぞれ50のサンプルがあります。
<br><br>

<center>
<img style="display:inline" src="./img/Iris_setosa.jpg" width="100"> Iris setosa (ヒオウギアヤメ)
<img style="display:inline" src="./img/iris_versiclor.jpg" width="100"> Iris versicolor (ブルーフラッグ)
<img style="display:inline" src="./img/Iris_virginica.jpg" width="100"> Iris virginica (バージニカ)
</center>

Let us load the iris dataset from the file `iris_data.csv`. (_csv_ stands for _comma separated values_).
<br>
The file contains one record per line with entries: flower type, sepal length, sepal width, petal length, petal width
<br>
(The lengths are measured in centimeters.)

ファイル`iris_data.csv`からアヤメのデータを読みだしてみましょう。 （_csv_ は _comma separated values（カンマ区切り値）_の省略です）。
<br>
ファイルには、それぞれの行に1つの花の記録が入っています。値が次の順番で書かれています：花の種類、がくの長さ、がくの幅、花びらの長さ、花びらの幅
<br>
（長さはセンチメートルで表しています。）

Here are the first lines of the file / ファイルの最初の行は次のとおりです
<br>
0.0,5.1,3.5,1.4,0.2
<br>
0.0,4.9,3.0,1.4,0.2
<br>
0.0,4.7,3.2,1.3,0.2
<br>
0.0,4.6,3.1,1.5,0.2
<br>
...

To read the values from a file we can use the function `genfromtxt` from `numpy` .

ファイルから値を読み取るには、`numpy`の関数`genfromtxt`を使用できます。

In [24]:
iris = np.genfromtxt('iris_data.csv', delimiter=',')

Now, the variable `iris` contains the iris dataset. The variable is a numpy array.

これで、変数 `iris`にはアヤメのデータセットが入っています。変数はnumpy配列です。

In [25]:
type(iris)

numpy.ndarray

There are 150 rows and 5 columns.

150行と5列があります。

In [26]:
iris.shape

(150, 5)

Summary of the data structure / データ構造の概要

     1.花のタイプ
     2.がく片の長さ
     3.がく片の幅
     4.花びらの長さ
     5.花びらの幅

-。
     -アイリスセトサの場合は50（0）
     -アイリスバーシクラー用50（1）
     -50はアイリスヴァージニカ（2）

- Each row corresponds to one data point and contains five values / 各行は1つのサンプルに対応し、5つの値が含まれます:
    1. flower type / 花の種類
    2. sepal length / がくの長さ
    3. sepal width / がくの幅
    4. petal length / 花びらの長さ
    5. petal width / 花びらの幅
- Each of the species has 50 data points / それぞれの花の種類には50のサンプルがあります
    - 0 = iris setosa / ヒオウギアヤメ
    - 1 = iris versiclor / ブルーフラッグ
    - 2 = iris virginica / バージニカ

Let us print the data / データをプリントしてみましょう

In [27]:
print(iris)

[[0.  5.1 3.5 1.4 0.2]
 [0.  4.9 3.  1.4 0.2]
 [0.  4.7 3.2 1.3 0.2]
 [0.  4.6 3.1 1.5 0.2]
 [0.  5.  3.6 1.4 0.2]
 [0.  5.4 3.9 1.7 0.4]
 [0.  4.6 3.4 1.4 0.3]
 [0.  5.  3.4 1.5 0.2]
 [0.  4.4 2.9 1.4 0.2]
 [0.  4.9 3.1 1.5 0.1]
 [0.  5.4 3.7 1.5 0.2]
 [0.  4.8 3.4 1.6 0.2]
 [0.  4.8 3.  1.4 0.1]
 [0.  4.3 3.  1.1 0.1]
 [0.  5.8 4.  1.2 0.2]
 [0.  5.7 4.4 1.5 0.4]
 [0.  5.4 3.9 1.3 0.4]
 [0.  5.1 3.5 1.4 0.3]
 [0.  5.7 3.8 1.7 0.3]
 [0.  5.1 3.8 1.5 0.3]
 [0.  5.4 3.4 1.7 0.2]
 [0.  5.1 3.7 1.5 0.4]
 [0.  4.6 3.6 1.  0.2]
 [0.  5.1 3.3 1.7 0.5]
 [0.  4.8 3.4 1.9 0.2]
 [0.  5.  3.  1.6 0.2]
 [0.  5.  3.4 1.6 0.4]
 [0.  5.2 3.5 1.5 0.2]
 [0.  5.2 3.4 1.4 0.2]
 [0.  4.7 3.2 1.6 0.2]
 [0.  4.8 3.1 1.6 0.2]
 [0.  5.4 3.4 1.5 0.4]
 [0.  5.2 4.1 1.5 0.1]
 [0.  5.5 4.2 1.4 0.2]
 [0.  4.9 3.1 1.5 0.1]
 [0.  5.  3.2 1.2 0.2]
 [0.  5.5 3.5 1.3 0.2]
 [0.  4.9 3.1 1.5 0.1]
 [0.  4.4 3.  1.3 0.2]
 [0.  5.1 3.4 1.5 0.2]
 [0.  5.  3.5 1.3 0.3]
 [0.  4.5 2.3 1.3 0.3]
 [0.  4.4 3.2 1.3 0.2]
 [0.  5.  3

## Try  it yourself ! / 自分で試そう！

[Click here](session2-playground.ipynb) to open a sample notebook and test some data manipulation

[ここをクリックして](session2-playground.ipynb)サンプルのノートブックを開いて、データ処理を試してみてください