## Session5 - playground

- Import the necessary packages
- Load the iris dataset
- Create the observations `X` and labels `y`


- 必要なパッケージをインポートします
- アヤメのデータセットを読み込みます
- 観測値`X`とラベル`y`を作成します

In [1]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

# Load data
iris = np.genfromtxt('iris_data.csv', delimiter=',')

X = iris[:,1:]
y = iris[:,0]
print("X has shape:", X.shape)
print("y has shape:", y.shape)

X has shape: (150, 4)
y has shape: (150,)


## TASK 1: preparation

Copy your code for data preparation from day1, session4-playground1 (both TASK1 and TASK2) in the cell below and execute it.

以下のセルにday1のsession4-playground1からデータ準備用のコード（TASK1とTASK2の両方）をコピーして、実行してください。

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test  = train_test_split(X, y, test_size=0.4)
scaler = StandardScaler()
scaler.fit(X_train);

X_train_raw = X_train
X_train = scaler.transform(X_train_raw)
X_test_raw = X_test
X_test = scaler.transform(X_test_raw)

## TASK 2
- Create and train a linear support vector classifier


- 線形サポートベクトル分類器を作成し、トレーニングさせる

In [3]:
from sklearn.svm import LinearSVC
linear_SVC = LinearSVC()
linear_SVC.fit(X_train, y_train); 

## TASK 3
- Predict the labels for the test features


- テストデータのラベルを予測する

In [4]:
y_pred = linear_SVC.predict(X_test)

## TASK 4
- Show the confusion matrix
- Compute the accuracy (you should obtain more than 0.9 (90%) accuracy)


- 混同行列を表示する
- 精度を計算する（0.9（90％）以上の精度が得られるはずです）

In [5]:
from sklearn.metrics import confusion_matrix

CM = confusion_matrix(y_test, y_pred)
print(CM)

A = np.sum(np.diag(CM)) / np.sum(CM)
print("Accuracy: {:.02f}".format(A))

[[16  0  0]
 [ 0 21  0]
 [ 0  1 22]]
Accuracy: 0.98


## OPTIONAL 1
- Run the training another time and compare (tip: you can use `Cell -> Run All` from the menu)
- Change the proportion of test samples and see the impact on the performance


- トレーニングをもう一度実行して、結果を比較します（ヒント：メニューから`Cell -> Run All`を利用できます）
- テストサンプルの比率を変更し、パフォーマンスへの影響を確認する

### 結果
- トレーニングの回数を増やすと精度が向上した
    - 1回目: 0.92
    - 2回目: 0.96
  
- テストサンプルの比率を減らすと精度が向上した
    - テストサイズ0.5: 0.92
    - テストサイズ0.4: 0.98

## OPTIONAL 2

The splitting between training and testing set does not care if there is an "equal" number of each flower type in the sets.

- Write some code to split the dataset randomly and care about having an equal representation of each flower type (you can start from the code for manually spliting in the main notebook)
- Test the average performance of the classifier using this dataset splitting method

トレーニングセットとテストセットの分割は、セット内の各花の種類が「等しい」数であるかどうかを考慮していません。

- データセットをランダムに分割し、各花の種類の数が同じになるためのコードを実装してください（ヒント：メインのノートブックにある手動の分割のコードを元に開発できます）

- このデータセット分割方法を使用して、分類器の平均パフォーマンスを確認してください

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix

for i in range(0,3):
    # irisを花の種類ごとに前もって分割
    iris_splitted = iris[iris[:,0] == i, :]
    X_splitted = iris_splitted[:,1:]
    y_splitted = iris_splitted[:,0]
    # それぞれをランダムに分割
    X_train_splitted, X_test_splitted, y_train_splitted, y_test_splitted = train_test_split(X_splitted, y_splitted, test_size=0.5)
    # 統合
    if i == 0:
        X_train = X_train_splitted
        X_test = X_test_splitted
        y_train = y_train_splitted
        y_test = y_test_splitted
    else:
        X_train = np.concatenate([X_train, X_train_splitted])
        X_test = np.concatenate([X_test, X_test_splitted])
        y_train = np.concatenate([y_train, y_train_splitted])
        y_test = np.concatenate([y_test, y_test_splitted])

# あとはいつもどおり
scaler = StandardScaler()
scaler.fit(X_train);

X_train_raw = X_train
X_train = scaler.transform(X_train_raw)
X_test_raw = X_test
X_test = scaler.transform(X_test_raw)

linear_SVC = LinearSVC()
linear_SVC.fit(X_train, y_train); 
y_pred = linear_SVC.predict(X_test)


CM = confusion_matrix(y_test, y_pred)
A = np.sum(np.diag(CM)) / np.sum(CM)
print("Accuracy: {:.02f}".format(A))

Accuracy: 0.92
